spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/marketspace?allowMultiQueries=true&useSSL=false&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC&cacheCallableStmts=true&autoReconnect=true&rewriteBatchedStatements=true&profileSQL=false&logger=Slf4JLogger&maxQuerySizeToLog=20
    username: user
    password: password
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 5
      maximum-pool-size: 10
  jpa:
    generate-ddl: false
    show-sql: true
    properties:
      format_sql: true
    hibernate:
      ddl-auto: none
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
logging:
  level:
    com.juneox.marketspace : debug

app:
  market-space:
    file-store: ./sample